### PR TITLE
change url & path of gz_cmake2_vendor and gz_math6_vendor

### PR DESCRIPTION
**Pull request by homalozoa**
Signed-off-by: homalozoa <nx.tardis@gmail.com>

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17675/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12224/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18263/)

**Review by clalancette — APPROVED** [review]
Thanks for doing this!  Looks good to me with green CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17677/)

**Comment by ahcorde** [comment]
CI is green, @homalozoa thank you for your contribution

**Pull request merged**
