### PR TITLE
Upgrade Fast DDS to 2.1.x

### PR DESCRIPTION
**Pull request by EduPonz**
Signed-off-by: EduPonz <eduardoponz@eprosima.com>

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14304/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9093/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11990/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14409/)

**Comment by jacobperron** [comment]
I'm not sure why this particular failure is happening only on Windows:

> 12:04:26 C:\ci\ws\install\include\fastdds/rtps/builtin/discovery/endpoint/EDP.h(32,10): fatal error C1083: Cannot open include file: 'foonathan/memory/container.hpp': No such file or directory (compiling source file C:\ci\ws\src\ros2\rmw_fastrtps\rmw_fastrtps_shared_cpp\src\participant.cpp) [C:\ci\ws\build\rmw_fastrtps_shared_cpp\rmw_fastrtps_shared_cpp.vcxproj]

**Comment by hidmic** [comment]
Retrying full CI after https://github.com/ros2/rmw_fastrtps/pull/524: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14753/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9503/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12417/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14900/)

**Comment by jacobperron** [comment]
The CI results LGTM. I believe all of those failures/warnings are pre-existing.

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
@hidmic Thanks for helping move this forward :bow:

**Pull request merged**
