### PR TITLE
Ignore C typesupport packages

### PR DESCRIPTION
**Pull request by jacquelinekay**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Beside the order (which should be alphabetical) lgtm.

**Comment by jacquelinekay** [comment]
Connext-only (ignore Opensplice, FastRTPS):
http://ci.ros2.org/job/ci_linux/934/

**Comment by dirk-thomas** [comment]
You want to test OpenSplice-only: http://ci.ros2.org/job/ci_osx/785/

**Comment by dirk-thomas** [comment]
FastRTPS-only: http://ci.ros2.org/job/ci_linux/935/

**Comment by dirk-thomas** [comment]
Both jobs have passed their critical point already. +1.

**Pull request merged**
