### PR TITLE
Dashing - workaround to get ros2 on Raspberry Pi 4 

### PR DESCRIPTION
**Pull request by supagas**
add every packages that dont build "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -latomic")" 
in the CMakeLists.txt after this the packages will not build either, but it will work after this.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please clarify the intention of your PR. The `ros2.repos` file on the `master` branch targets the next release which will be Foxy. Did you intend to target the `dashing` branch instead?

**Comment by wjwwood** [comment]
I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Comment by Reubenyuhe** [comment]
I still get the linking problem 
`/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `__atomic_fetch_add_8'`
when I try to compile ROS2-foxy on my RPI3B+ Buster. I've tried set
 `--cmake-args -DCMAKE_CXX_FLAGS=-latomic -DOPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic`
 like it was mentioned in following case while compiling OpenCV 4.1.2 but it didn't work. 
[Undefined reference to __atomic_xxx #15278](https://github.com/opencv/opencv/issues/15278)

I tried locate the libatomic.so with `sudo find / -name 'libatomic.so'`
and got
`/usr/lib/gcc/arm-linux-gnueabihf/7/libatomic.so
/usr/lib/gcc/arm-linux-gnueabihf/5/libatomic.so
/usr/lib/gcc/arm-linux-gnueabihf/8/libatomic.so`
as result.

My OS:
`root@raspberrypi:~# cat /etc/os-release`
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"`
`NAME="Raspbian GNU/Linux"`
`VERSION_ID="10"`
`VERSION="10` (buster)"
`VERSION_CODENAME=buster`
`root@raspberrypi:~# uname -a
Linux raspberrypi 4.19.71-rt24-v7+ #1 SMP PREEMPT RT Thu Apr 2 13:17:19 CEST 2020 armv7l GNU/Linux`

**Comment by fujitatomoya** [comment]
I am not sure if Raspbian is supported as ros2 supported platform.

btw, using ubuntu18.04 and raspi 4 works w/o any problems, we've been working on that.

**Comment by sloretz** [comment]
@Reubenyuhe please open a question on https://answers.ros.org . It's very easy to miss new comments on closed github PRs. When you open your question, be sure to include if the code you're trying to build has https://github.com/ros2/rcutils/pull/172 or https://github.com/ros2/rcutils/pull/178

**Comment by Reubenyuhe** [comment]
@sloretz Thanks. I will do that.

**Pull request closed without merging**
