### PR TITLE
Update to ament_cmake 2.0.3

### PR DESCRIPTION
**Pull request by cottsay**
This release contains critical fixes for the `ament_cmake_vendor_package` package.

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
This looks OK to me, but if we are going to do this update we should probably do a patch release and consider also releasing:

* `rqt_bag`
* `launch`
* `rclcpp`
* `rclpy`
* `ros2cli`
* `rosbag2`
* `rosidl`
* `rviz`

@Yadunund thoughts?

**Comment by cottsay** [comment]
Do we no longer update this file asynchronously as core packages are released? If this isn't the right workflow, we can just close this PR. My only goal is to make `ament_cmake_vendor_package` usable for RMF as soon as reasonably possible. If a patch release is necessary, I'm inclined to leave that up to the ROSbossen for Iron and Humble.

**Comment by clalancette** [comment]
> Do we no longer update this file asynchronously as core packages are released?

My recollection is that only the ROS bosses ever update the `<distro>-release` branch.  And looking back into the history of `foxy-release`, `galactic-release`, `humble-release`, and `iron-release`, that does seem to be the case.  Personally I think that makes the most sense, as updates here should typically coincide with a patch release.

But I'll let @Yadunund make the final call here.

**Comment by clalancette** [comment]
This got bumped in #1456 , so closing this PR out.

**Pull request closed without merging**
