### PR TITLE
Foxy release versions 2020-12-11

### PR DESCRIPTION
**Pull request by jacobperron**
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13255/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8183/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10970/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13285/)

Packaging:
* Linux [Build Status](https://ci.ros2.org/job/ci_packaging_linux/440/)
* Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_packaging_linux-aarch64/67/)
* macOS [Build Status](https://ci.ros2.org/job/ci_packaging_osx/79/)
* Windows [Build Status](https://ci.ros2.org/job/ci_packaging_windows/168/)
* Windows Debug [Build Status](https://ci.ros2.org/job/ci_packaging_windows/169/)
* CentOS [Build Status](https://ci.ros2.org/job/ci_packaging_linux-centos/27/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
It's probably worth trying to backport the CMake warning fixes for the next patch release so the packaging jobs can be green.

**Comment by jacobperron** [comment]
> It's probably worth trying to backport the CMake warning fixes for the next patch release so the packaging jobs can be green.

I agree. I've also already opened up a backport for the compiler warning that shows up in release builds: https://github.com/ros2/rmw_fastrtps/pull/494

**Comment by jacobperron** [comment]
@nuclearsandwich Can you point me to the PR(s) that fix the cmake warnings?

**Comment by clalancette** [comment]
@jacobperron You'll need (at least) the following:

1.  Update Fast-CDR to v1.0.17
1.  Backport https://github.com/ros2/orocos_kinematics_dynamics/pull/17
1.  Backport https://github.com/ros/urdfdom_headers/pull/67
1.  Backport https://github.com/ros2/rosbag2/pull/579
1.  Backport https://github.com/ament/googletest/pull/11

**Pull request merged**
