### PR TITLE
add ros/angles and ros-perception/laser_geometry

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/rviz#238

### CODE REVIEW

**Comment by dhood** [comment]
merging to get builds working again

**Comment by wjwwood** [comment]
Damn sorry, that’s the second time I’ve done that :/ thanks @dhood

**Comment by dhood** [comment]
no problem, easy fixed

**Comment by mikaelarguedas** [comment]
@wjwwood It looks like the angles package is not required anymore https://github.com/ros-perception/laser_geometry/commit/c029efcdd633df8b4935897cabeb95e31abddc14#diff-34ae68f4adad56c25c5bc05dcb64794e. Can we remove it from here ?
Should it be released anyway?

**Comment by wjwwood** [comment]
If it’s not required I guess we can remove it.

**Comment by mikaelarguedas** [comment]
:+1: 
I'll remove it from CI but release it in bouncy so that it's availab le to users and is tested on dev jobs. It just won't be tested on the other platforms anymore but will save some ci time

**Pull request merged**
