### PR TITLE
add installing poco to the linux docker image

### PR DESCRIPTION
**Pull request by wjwwood**
CI:

- http://ci.ros2.org/job/ros2_batch_ci_linux/481/
- http://ci.ros2.org/job/ros2_batch_ci_osx/382/
- http://ci.ros2.org/job/ros2_batch_ci_windows/533/

### CODE REVIEW

**Comment by tfoote** [comment]
ci failed: 

```
08:48:38 === ./src/vendor/class_loader (git) ===
08:48:38 fatal: Needed a single revision
08:48:38 invalid upstream master
```

**Comment by wjwwood** [comment]
The problem is this command:

```
"/home/rosbuild/ci_scripts/workspace/venv/bin/python" "/home/rosbuild/ci_scripts/workspace/venv/bin/vcs" custom . --git --args rebase master
```

Which is meant to rebase (? maybe that should be merge anyways) the branch being tested against master. But this doesn't work for class_loader which neither has a master branch nor is the branch being tested being proposed to be pulled against the default branch.

I think this call needs to try and rebase against the version which is in the original `ros2.repos` file. I'll try to make a patch to realize this.

**Comment by wjwwood** [comment]
Ok, I made an attempt at fixing this. New CI:

- http://ci.ros2.org/job/ros2_batch_ci_linux/483/
- http://ci.ros2.org/job/ros2_batch_ci_osx/384/
- http://ci.ros2.org/job/ros2_batch_ci_windows/536/

**Comment by wjwwood** [comment]
I did the wrong test branch:

- http://ci.ros2.org/job/ros2_batch_ci_linux/484/
- http://ci.ros2.org/job/ros2_batch_ci_osx/385/
- http://ci.ros2.org/job/ros2_batch_ci_windows/537/

**Comment by wjwwood** [comment]
Replacement Linux CI, after fixing docker file:

- http://ci.ros2.org/job/ros2_batch_ci_linux/485/

**Comment by wjwwood** [comment]
Fixed another bug in the ci_scripts changes:

- http://ci.ros2.org/job/ros2_batch_ci_linux/487/

**Comment by wjwwood** [comment]
And OS X:

- http://ci.ros2.org/job/ros2_batch_ci_osx/386/

**Comment by wjwwood** [comment]
There are quite a few new warnings generated on Windows by `poco` (we build it from source on Windows), `console_bridge`, and `class_loader`.

**Comment by gerkey** [comment]
If the warnings in `console_bridge` and `class_loader` are obviously relevant and/or important, fix them.  Otherwise, suppress them for now.  We won't fix all warnings in all code that we use.

**Comment by dirk-thomas** [comment]
The CI code has been moved to a separate repo. Since the code has diverged and is not mergable as-is I haven't recreated the PR in the new repo. But the branch is still there: https://github.com/ros2/ci/tree/ci_scripts_add_class_loader

**Pull request closed without merging**
