### PR TITLE
Add topic statistics dependency

### PR DESCRIPTION
**Pull request by prajakta-gokhale**
Add remaining dependency of topic statistics to ros2.repos.

This is blocked on
* [x] ~~https://github.com/ros2/ros2/pull/896~~ https://github.com/ros2/rcl_interfaces/pull/98
* [ ] https://github.com/ros-tooling/aws-roadmap/issues/248
* [x] https://github.com/ros-tooling/aws-roadmap/issues/249

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
CI up-to new package:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10269/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5807/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8351/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10163/)

**Comment by prajakta-gokhale** [comment]
@wjwwood please take a look!

**Comment by wjwwood** [comment]
Looks like there's a test failure: https://ci.ros2.org/job/ci_linux/10269/testReport/junit/(root)/projectroot/copyright/

**Comment by dabonnie** [comment]
Should be gtg with the most recent PR.

**Comment by wjwwood** [comment]
Please rerun CI.

**Comment by prajakta-gokhale** [comment]
Rerun after copyright fix:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10280/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5816/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8361/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10176/)

**Comment by prajakta-gokhale** [comment]
@wjwwood all test failures are now fixed.

**Comment by wjwwood** [comment]
Is this new compiler warning on Windows not due to this pr? https://ci.ros2.org/job/ci_windows/10185/msbuild/new/

**Comment by prajakta-gokhale** [comment]
> Is this new compiler warning on Windows not due to this pr? https://ci.ros2.org/job/ci_windows/10185/msbuild/new/

Yes, that is the one fixed in https://github.com/ros-tooling/libstatistics_collector/pull/6.

**Comment by wjwwood** [comment]
Ah, have you run CI since then? I just really don't want to merge something that takes us backwards towards green CI after all the work folks have put into getting it green again.

**Comment by prajakta-gokhale** [comment]
With latest changes:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10297/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5831/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8377/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10194/)

**Comment by prajakta-gokhale** [comment]
> Ah, have you run CI since then? I just really don't want to merge something that takes us backwards towards green CI after all the work folks have put into getting it green again.

That's fair. Started another round of CI which should have no new warnings.

**Comment by wjwwood** [comment]
Thanks I'll keep an eye out and merge it when it's back.

**Pull request merged**
