### PR TITLE
add optional ament args to job parameters

### PR DESCRIPTION
**Pull request by dirk-thomas**
Add parameter for ament arguments to Jenkins jobs. It will e.g.:
* enable to select only specific tests (`-R test_services_cpp__rmw_opensplice_cpp`)
* run tests repeatedly (`--repeat-until-fail 100`) (if the CMake version used supports it)

http://ci.ros2.org/job/ros2_batch_ci_osx/328/

### CODE REVIEW

**Comment by wjwwood** [comment]
Linked CI job failed due to the slave going offline during the build.

**Comment by dirk-thomas** [comment]
This patch can be merged. The arguments are passed correctly to ament:

* http://ci.ros2.org/job/ros2_batch_ci_linux/421/consoleFull#console-section-157
* http://ci.ros2.org/job/ros2_batch_ci_osx/330/consoleFull#console-section-157

But ament is currently not handling the arguments with white spaces correctly...

**Comment by dirk-thomas** [comment]
This patch can be merged. The arguments are passed correctly to ament:

* http://ci.ros2.org/job/ros2_batch_ci_linux/421/consoleFull#console-section-157
* http://ci.ros2.org/job/ros2_batch_ci_osx/330/consoleFull#console-section-157

But ament is currently not handling the arguments with white spaces correctly: ament/ament_tools#55

**Comment by wjwwood** [comment]
lgtm

**Pull request merged**
