### PR TITLE
change default behavior for Windows jobs to reflect no multi vendor building

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/ros2#150

I've already pushed the changes to the server so we can see if the nightly jobs are fixed. Here is an output of the job config diffs:

```diff
Connecting to Jenkins 'http://ci.ros2.org/'
Connected to Jenkins version '1.638'
Skipped 'ros2_batch_ci_linux' because the config is the same
Skipped 'ros2_packaging_linux' because the config is the same
Skipped 'ros2_batch_ci_linux_nightly' because the config is the same
Skipped 'ros2_batch_ci_osx' because the config is the same
Skipped 'ros2_packaging_osx' because the config is the same
Skipped 'ros2_batch_ci_osx_nightly' because the config is the same
Updating job 'ros2_batch_ci_windows'
    <<<
    --- remote config
    +++ new config
    @@ -41 +41 @@
    -          <defaultValue>true</defaultValue>
    +          <defaultValue>false</defaultValue>
    >>>
The Jenkins master does not require a crumb
Skipped 'ros2_packaging_windows' because the config is the same
Updating job 'ros2_batch_ci_windows_nightly'
    <<<
    --- remote config
    +++ new config
    @@ -41 +41 @@
    -          <defaultValue>true</defaultValue>
    +          <defaultValue>false</defaultValue>
    >>>
Creating job 'ros2_batch_ci_windows_connext_dynamic'
Creating job 'ros2_packaging_windows_connext_dynamic'
Creating job 'ros2_batch_ci_windows_connext_dynamic_nightly'
Creating job 'ros2_batch_ci_windows_connext_static'
Creating job 'ros2_packaging_windows_connext_static'
Creating job 'ros2_batch_ci_windows_connext_static_nightly'
Updating job 'ros2_batch_ci_launcher'
    <<<
    --- remote config
    +++ new config
    @@ -109,0 +110,16 @@
    +            <hudson.plugins.parameterizedtrigger.BooleanParameters>
    +              <configs>
    +                <hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +                  <name>CI_USE_CONNEXT</name>
    +                  <value>false</value>
    +                </hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +                <hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +                  <name>CI_DISABLE_CONNEXT_STATIC</name>
    +                  <value>false</value>
    +                </hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +                <hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +                  <name>CI_DISABLE_CONNEXT_DYNAMIC</name>
    +                  <value>false</value>
    +                </hudson.plugins.parameterizedtrigger.BooleanParameterConfig>
    +              </configs>
    +            </hudson.plugins.parameterizedtrigger.BooleanParameters>
    >>>

```

For now I changed the launcher to only launch an opensplice job for Windows and it does so even if you select use connext by overriding those boolean job values explicitly.

Also I created two new Windows jobs, one for connext static and the other for dynamic, but left the Windows opensplice job called just `*_windows` so that the job history was preserved there.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I don't think we have to preserve the *links* of previous runs. In order to preserve the build history you can simply rename the existing `*_windows` jobs to `*_windows_opensplice`.

**Comment by dirk-thomas** [comment]
I also adjusted the trigger time to not overlap with our nightly network reset (2da08b464ad17611925a503da051257dc358db6b). Please rebase this branch.

**Comment by dirk-thomas** [comment]
The new Windows job names lead to the paths to be too long: http://ci.ros2.org/job/ros2_batch_ci_windows_connext_dynamic/1/console#console-section-11

**Comment by wjwwood** [comment]
Ok, I rebased, changed the name to `_windows_opensplice` and modified the launcher to launch all three Windows jobs (which should partially satisfy https://github.com/ros2/ros2/issues/151).

I already committed the changes and I also added a permanently moved rewrite rule for the change in the windows jobs name, and noted it here: https://github.com/ros2/ros2/wiki/CI-Server-Setup#temporary-rewrite-for-changed-job-name

**Comment by wjwwood** [comment]
Basically the solution is to make the directory name shorter: http://stackoverflow.com/questions/11434206/visual-studio-unknown-build-error-the-fully-qualified-name-must-be-less-than-26

So I:
- Changed the Jenkins folder to `C:\J` from `C:\Jenkins` on the Windows build slave
- Changed the workspace folder the ci job makes to be `ws` (except when putting white space in)
- Changed the job names to be shorter
 - `ros2_batch_ci_*` => `ci_*`
 - `ros2_batch_ci_*_nightly` => `nightly_*`
 - `ros2_packaging_*` => `packaging_*`

I setup modrewrite rules from the old job names to the new names. I'm testing stuff out now and if it's working then I'll merge this.

**Comment by wjwwood** [comment]
The farm looks good to me, so I'll merge this. Comment if anyone notices anything wrong.

**Comment by dirk-thomas** [comment]
There seems to be an extra Windows nightly job (http://ci.ros2.org/view/nightly/job/nightly_windows/) but none for OSX?

**Comment by wjwwood** [comment]
The OS X job was there I apparently just didn't add it back to the view. I never renamed the windows nightly job when renamed the ci version. So I deleted the `nightly_windows_opensplice` job (it had only four builds from the past four days) and renamed `nightly_windows` to be `nightly_windows_opensplice`. Should be good now.

**Comment by dirk-thomas** [comment]
Instead of assigning jobs manually to a view you should use the regex already in place to match the new names. I updated the views accordingly.

**Comment by dirk-thomas** [comment]
I also reconfigured the `nightly_windows_opensplice` job. It was running at the wrong time last night and also still using the long workspace path.

**Comment by dirk-thomas** [comment]
What about these two jobs?
* http://ci.ros2.org/job/ci_osx_nightly/
* http://ci.ros2.org/view/packaging/job/packaging_windows/

**Comment by wjwwood** [comment]
Thanks for pointing those out, I renamed `packaging_windows` to `packaging_windows_opensplice` (which I deleted because it had no history) and I did `--commit` to ensure the renamed job was up-to-date.

For the osx job I similarly renamed `ci_osx_nightly` to `nightly_osx` and deleted the job that was named that as it had very little history and used `--commit` to make sure it was up-to-date.

**Pull request merged**
