### PR TITLE
use Xenial instead of Trusty

### PR DESCRIPTION
**Pull request by dirk-thomas**
This should only be merged once we switched to Xenial.

### CODE REVIEW

**Comment by wjwwood** [comment]
There was some discussion here on the RTI forums about 16.04 support:

https://community.rti.com/forum-topic/ubuntu-1604-support

Apparently there were some issues, but it wasn't clear if they got them resolved or not. Might be worth investigating before deciding to jump our farm over to 16.04.

**Comment by dirk-thomas** [comment]
I am using Xenial since mid of March and haven't seen any issue while working on ROS 2.

**Comment by dirk-thomas** [comment]
The latest build (http://ci.ros2.org/job/ci_linux/1430/) looks good except that the `rclpy` tests are failing.

**Comment by dirk-thomas** [comment]
The `rclpy` test failures are being resolved with ros2/rosidl#151.

**Comment by jacquelinekay** [comment]
+1

**Comment by dirk-thomas** [comment]
It might be a good idea to install ROS 1 Kinetic instead of failing to find Indigo... 647ace8ce6e5c1ab551787997c357f1e1266cecd

**Comment by dirk-thomas** [comment]
And `rosbag` doesn't need to be patched for `lz4` anymore: 91962ee562e64b648ab6d097642d2c42e454e669

**Pull request merged**
