### PR TITLE
Update ros2_tracing to 1.0.1

### PR DESCRIPTION
**Pull request by christophebedard**
Contains some minor fixes.

See: https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing/-/compare/1.0.0...1.0.1

### CODE REVIEW

**Comment by wjwwood** [comment]
The warnings on Linux, like this one:

- https://ci.ros2.org/job/ci_linux/11018/clang/new/fileName.1221180622/

Look like a false positive from the warning extractor plugin, probably due to changes in cyclone, here's the context for one of them:

```
test 130
          Start  130: CUnit_ddssec_access_control_config_parameters_file

130: Test command: /home/jenkins-agent/workspace/ci_linux/ws/build/cyclonedds/bin/cunit_security_core "-s" "ddssec_access_control" "-t" "config_parameters_file"
130: Environment variables: 
130:  LD_LIBRARY_PATH=/home/jenkins-agent/workspace/ci_linux/ws/build/cyclonedds/lib:/home/rosbuild/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:
130: Test timeout computed to be: 10
130: 
130: 
130:      CUnit - A unit testing framework for C - Version 2.1-3
130:      http://cunit.sourceforge.net/
130: 
130: 1591295148.668600 running test config_parameters_file: existing files
130: 1591295148.668607 init domain 0
130: 1591295148.675579 init domain 1
130: 1591295148.681051 [0] dq.builtin: Remote secure participant ac8fdda9:aa4e2b3d:653f8943:1c1 not allowed
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.684291 running test config_parameters_file: non-existing files
130: 1591295148.684299 init domain 0
130: 1591295148.689177 [0] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_ca_non_existing.pem(code: 117)
130: 1591295148.689201 init domain 1
130: 1591295148.693652 [1] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_ca_non_existing.pem(code: 117)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.694774 running test config_parameters_file: non-existing governance file
130: 1591295148.694783 init domain 0
130: 1591295148.699501 [0] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_governance_non_existing.p7s(code: 117)
130: 1591295148.699520 init domain 1
130: 1591295148.703995 [1] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_governance_non_existing.p7s(code: 117)
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.705245 running test config_parameters_file: non-existing permissions file
130: 1591295148.705255 init domain 0
130: 1591295148.709856 [0] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_non_existing.p7s(code: 117)
130: 1591295148.709874 init domain 1
130: 1591295148.714324 [1] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_non_existing.p7s(code: 117)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.715458 running test config_parameters_file: non-existing permissions ca file
130: 1591295148.715468 init domain 0
130: 1591295148.720006 [0] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_ca_non_existing.pem(code: 117)
130: 1591295148.720024 init domain 1
130: 1591295148.724481 [1] cunit_secu: Error occurred while validating local permissions: File could not be found, opened or is empty, path: /home/jenkins-agent/workspace/ci_linux/ws/src/eclipse-cyclonedds/cyclonedds/src/security/core/tests/common/etc/default_permissions_ca_non_existing.pem(code: 117)
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.725415 running test config_parameters_file: empty governance
130: 1591295148.725425 init domain 0
130: 1591295148.729963 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.729984 init domain 1
130: 1591295148.734311 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.735406 running test config_parameters_file: empty permissions
130: 1591295148.735416 init domain 0
130: 1591295148.739909 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.739928 init domain 1
130: 1591295148.744240 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.745385 running test config_parameters_file: empty permissions ca
130: 1591295148.745394 init domain 0
130: 1591295148.749936 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.749957 init domain 1
130: 1591295148.754374 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.755547 running test config_parameters_file: all empty
130: 1591295148.755555 init domain 0
130: 1591295148.760360 init domain 1
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.769924 running test config_parameters_file: invalid governance uri type
130: 1591295148.769933 init domain 0
130: 1591295148.774704 [0] cunit_secu: Error occurred while validating local permissions: Failed to parse PKCS7 SMIME document: 139621844647744:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:../crypto/asn1/asn_mime.c:399:
130: (code: 127)
130: 1591295148.774724 init domain 1
130: 1591295148.780755 [1] cunit_secu: Error occurred while validating local permissions: Failed to parse PKCS7 SMIME document: 139621844647744:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:../crypto/asn1/asn_mime.c:399:
130: (code: 127)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.783122 running test config_parameters_file: permissions ca type data
130: 1591295148.783131 init domain 0
130: 1591295148.788610 init domain 1
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.796857 running test config_parameters_file: no governance element
130: 1591295148.796866 init domain 0
130: 1591295148.801490 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.801510 init domain 1
130: 1591295148.805905 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 1591295148.807060 running test config_parameters_file: no permissions element
130: 1591295148.807068 init domain 0
130: 1591295148.811727 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.811747 init domain 1
130: 1591295148.816211 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97ba9d4a0): all valid
130: returns result (impl 0x55f97bae58a0): all valid
130: 1591295148.817293 running test config_parameters_file: no permissions ca element
130: 1591295148.817302 init domain 0
130: 1591295148.821923 [0] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: 1591295148.821944 init domain 1
130: 1591295148.826475 [1] cunit_secu: Error occurred while validating local permissions: Governance, Permissions and Permissions CA properties do not exist properly. Either all must be empty or all must be valid(code: 116)
130: returns result (impl 0x55f97bae58a0): all valid
130: returns result (impl 0x55f97ba9d4a0): all valid
130: 
130: 
130: Run Summary:    Type  Total    Ran Passed Failed Inactive
130:               suites     10      1    n/a      0        9
130:                tests     62      1      1      0       12
130:              asserts    330    330    330      0      n/a
130: 
130: Elapsed time =    0.155 seconds
 130/1089 Test  #130: CUnit_ddssec_access_control_config_parameters_file .............................................   Passed    0.16 sec
```

**Comment by wjwwood** [comment]
macOS has the assimp cmake warning and the same false positive compiler warning as Linux.

However, it also has some segfaults in tests which may be new:

https://ci.ros2.org/job/ci_osx/8976/testReport/(root)/projectroot/test_publisher_subscription_count_api/

I'll have to look into those and the changes to ros2_tracing to see if it could be an issue there.

**Comment by wjwwood** [comment]
On Windows the test failures look like false positives to do with CUnit, and other known flaky tests.

**Comment by wjwwood** [comment]
The macOS test failures are on nightly too, so that doesn't seem to be new:

https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1977/testReport/junit/(root)/projectroot/test_publisher_subscription_count_api/

So I think this is good to go.

**Comment by jacobperron** [comment]
@wjwwood Thanks for looking into it!

**Pull request merged**
