### PR TITLE
Updating CycloneDDS version for Dashing

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Can I get a CI run, @nuclearsandwich?

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Ping @nuclearsandwich

**Comment by nuclearsandwich** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12606/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7568/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12527/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/12528/)

**Comment by JWhitleyWork** [comment]
@nuclearsandwich Thanks for the CI run! Is it normal for everything to pass except those tests?

**Comment by JWhitleyWork** [comment]
@nuclearsandwich Ping ping

**Comment by nuclearsandwich** [comment]
> Thanks for the CI run! Is it normal for everything to pass except those tests?

ROS 2 CI always runs the latest linter versions but we don't backport linter-only changes to released distros. I run Dashing full CI with linters disabled but there are some which aren't properly tagged and so still run and fail.

These two tests:

* https://ci.ros2.org/job/ci_linux/12606/testReport/rcl_action/TestActionGraphFixture__rmw_cyclonedds_cpp/test_action_get_client_names_and_types_by_node/
* https://ci.ros2.org/job/ci_linux/12606/testReport/rcl_action/TestActionGraphFixture__rmw_cyclonedds_cpp/test_action_get_server_names_and_types_by_node/

are failing for CycloneDDS but passing for other rmw so that might be some concern although looking at CI from patch release 7 it is not a recent regression https://github.com/ros2/ros2/pull/982#issuecomment-662107088

**Comment by JWhitleyWork** [comment]
@joespeed See note above from @nuclearsandwich. Can you coordinate verification/troubleshooting the two valid failures?

**Comment by nuclearsandwich** [comment]
These issues are not new to Dashing. I would suggest that we either proceed with the 0.7 update in Dashing so that the update can spend some time in the testing repo or we plan to leave CycloneDDS as is for the upcoming sync. What are your thoughts @JWhitleyWork?

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-dashing-sync-2020-10-27/16839/1

**Comment by JWhitleyWork** [comment]
@nuclearsandwich I'm good with proceeding with the 0.7.0 in Dashing for the upcoming sync.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
