### PR TITLE
Update ros2_tracing to 0.3.0 for Foxy

### PR DESCRIPTION
**Pull request by christophebedard**
Includes various improvements, including a fix for `cppcheck` on Focal (also see https://github.com/ros2/rclcpp/pull/1000).

cc @brawner

### CODE REVIEW

**Comment by christophebedard** [comment]
I'm guessing I can wait a bit before doing the `rosdistro` release. Otherwise just let me know.

**Comment by jacobperron** [comment]
Thanks @christophebedard, it should be okay to wait to do a release into rosdistro.

I've queued CI jobs:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9542/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5249/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7795/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9466/)

As well as one on Ubuntu Focal:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9543/)

**Comment by christophebedard** [comment]
> As well as one on Ubuntu Focal:
> * Linux [Build Status](http://ci.ros2.org/job/ci_linux/9543/)

@jacobperron I think this should point to 9542 instead of 9543 :smiley: 

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/9542/)

**Comment by jacobperron** [comment]
You're right. It happens when there are too many jobs in the queue. I've updated my comment.

**Comment by christophebedard** [comment]
thanks @jacobperron!

**Pull request merged**
