### PR TITLE
Add Topic Statistics Dependencies

### PR DESCRIPTION
**Pull request by dabonnie**
Adds dependencies required by https://github.com/ros2/rclcpp/pull/1050

This is ready to merge once https://github.com/ros-tooling/aws-roadmap/issues/248 and https://github.com/ros-tooling/aws-roadmap/issues/249 are complete

Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
With https://github.com/ros-tooling/metrics_statistics_msgs/pull/1 merged, we have one dependency of Topic Statistics in this new repo. Adding it to the ros2.repos file.

**Comment by prajakta-gokhale** [comment]
@wjwwood @thomas-moulard please take a look!

**Comment by prajakta-gokhale** [comment]
> Should we wait to add the other library's repository?

We spit it into 2 PRs so that once we merge this we can run CI for the other one. `libstatistics_collector`(https://github.com/ros2/ros2/pull/897) depends on `metrics_statistics_msgs` (this PR).

**Comment by prajakta-gokhale** [comment]
@jacobperron could you please start CI for this PR?

**Comment by prajakta-gokhale** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10227/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5775/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8316/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10115/)

**Comment by prajakta-gokhale** [comment]
Package only CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10246/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5789/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8328/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10128/)

**Comment by dirk-thomas** [comment]
Interfaces which are being used by the client libraries are defined in `rcl_interfaces`. Why should we introduce a second package which becomes a dependency of `rcl` (currently `rclcpp` but clearly it will need to be pished down into `rcl` in the future)?

**Comment by dabonnie** [comment]
> Interfaces which are being used by the client libraries are defined in `rcl_interfaces`. Why should we introduce a second package which becomes a dependency of `rcl` (currently `rclcpp` but clearly it will need to be pished down into `rcl` in the future)?

Hi @dirk-thomas: the dependency was introduced in this `rclcpp` PR (https://github.com/ros2/rclcpp/pull/1050), where `metrics_statistics_msgs` is an `rclcpp` dependency. We discussed this offline with @wjwwood and we came to the conclusion that introducing the dependency as a separate repo (via https://github.com/ros-tooling/aws-roadmap/issues/249) was fine, with another reason being Topic Statistics is currently a C++ feature only.

**Comment by dirk-thomas** [comment]
> another reason being Topic Statistics is currently a C++ feature only.

Obviously that is only a short term state. As soon as possible the feature will be pushed down into `rcl` in order to provide the same statistics in other client libraries like `rclpy`. And at that point I question the decision to have two interface packages: `rcl_interfaces` and something containing interfaces for `rcl` but with a different name. Imo it goes against the rational we settled on to create `rcl_interfaces` in the first place.

**Comment by wjwwood** [comment]
I also advised putting this logic into `rcl` as the statistics feature isn't nearly as useful if only part of your system can contribute to it. I think this is a result of not having time to push it down. When this is a feature of `rcl`, I agree it would make sense to put it in `rcl_interfaces`. I would also support putting the new messages in `rcl_interfaces` now, to be honest. I just didn't push the point.

**Comment by dirk-thomas** [comment]
Lets not create a Foxy-only message package then but move the interfaces into `rcl_interfaces` now. That makes sure that code using them doesn't have to be changed / broken in G-turtle.

**Comment by wjwwood** [comment]
Sounds good to me, @dabonnie can you guys do that then? Sorry for the back and forth.

**Comment by prajakta-gokhale** [comment]
We don't have a plan to add topic statistics to rclpy yet, but I agree that in the long run having the messages for it in rcl is the right thing to do.

We will close this PR and move code from `metrics_statistics_msgs` to `rcl_interfaces`.

**Comment by prajakta-gokhale** [comment]
Opened https://github.com/ros2/rcl_interfaces/pull/98. @dabonnie we can close this.

**Comment by dabonnie** [comment]
Hey @dirk-thomas and @wjwwood can you please review https://github.com/ros2/rcl_interfaces/pull/98? I'll close this given the PR in `rcl_interfaces`.

**Pull request closed without merging**
