### PR TITLE
Added Python3 development package

### PR DESCRIPTION
**Pull request by esteve**
Just to make sure it gets installed on Linux.

### CODE REVIEW

**Comment by tfoote** [comment]
+1 we should simultaneously update the tutorials/install instructions on the wiki to keep them up to date.

**Comment by esteve** [comment]
@tfoote I've updated the instructions for Linux, I'm looking into how to install the -dev packages on Windows and Mac

**Comment by dirk-thomas** [comment]
Please provide links to the changes in the wiki (e.g. https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/5f708348af85e16810d01dc578786cebeaa77c9e...b89019bcc11d59c158044acb183f0e712f67636c) to make it easier to review the changes.

For the Linux instructions please keep the list in alphabetical order.

**Comment by esteve** [comment]
@dirk-thomas I noticed that the python packages are not in alphabetical order (e.g. python3-setuptools) and I assumed that it was because any new package would be added at the end. I've updated the line in:

https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/5f708348af85e16810d01dc578786cebeaa77c9e...8603879235faf7fd53d9e05ff8703f7392bb2146

**Pull request merged**
