### PR TITLE
add eProsima repos

### PR DESCRIPTION
**Pull request by dirk-thomas**
Adds the eProsima repos. Waiting for upstream fixes before merging this.

Connect to ros2/ros2#124

### CODE REVIEW

**Comment by tfoote** [comment]
pushing back to backlog while waiting for upstream.

**Comment by dirk-thomas** [comment]
The latest build looks much better: http://ci.ros2.org/job/ros2_batch_ci_linux/366/testReport/

Still waiting for upstream to resolve the remaining issues before trying it on other platforms.

**Comment by dirk-thomas** [comment]
This seems to be ready now. I guess we will address the few remaining test failures afterwards.

**Comment by dirk-thomas** [comment]
All CI jobs without FastRTPS:
* http://ci.ros2.org/job/ci_linux/781/
* http://ci.ros2.org/job/ci_osx/648/
* http://ci.ros2.org/job/ci_windows/828/

All CI jobs with FastRTPS:
* http://ci.ros2.org/job/ci_linux/782/
* http://ci.ros2.org/job/ci_osx/650/
* http://ci.ros2.org/job/ci_windows/829/

**Comment by gerkey** [comment]
@dirk-thomas How do you want to handle the failing tests for FastRTPS? Let them go for now and fix them later, or fix them before merging this PR?

**Comment by dirk-thomas** [comment]
I would vote to merge this now. And the tests get fixed when someone takes the time to do so.

**Pull request merged**
