### PR TITLE
Add mimick_vendor package to ros2.repos

### PR DESCRIPTION
**Pull request by Blast545**
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
CI (Adding remaining Tier1 CI after peer review):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11593/)

**Comment by Blast545** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11599/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6740/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9484/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11564/)

**Comment by dirk-thomas** [comment]
This breaks the Rolling CI builds (e.g. http://build.ros2.org/view/Rci/job/Rci__nightly-debug_ubuntu_focal_amd64/23/) since the package uses a key which is not a valid `rosdep` key: https://github.com/ros2/mimick_vendor/blob/7687045188b2329372ca2cf8c728370bb30f5a81/package.xml#L19

@Blast545 Please fix asap.

**Comment by dirk-thomas** [comment]
This change also introduced a CMake warning on Windows: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1639/msbuild/

@Blast545 Please address.

**Pull request merged**
