### PR TITLE
Updating CycloneDDS for Eloquent

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Updating Cyclone with 0.7.0 release.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@mjcarroll Would you mind kicking off a CI run when you have a minute?

**Comment by JWhitleyWork** [comment]
Ping @mjcarroll

**Comment by JWhitleyWork** [comment]
@mjcarroll Ping ping

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12696/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7657/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10410/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12641/)

**Comment by joespeed** [comment]
@mjcarroll thanks for helping @JWhitleyWork by running this. Is this a good run or not? 

Looked like almost all of 190 failed tests are flake8. Dashing doesn't show such issue so what might be different? Dashing & Eloquent job probably have same rmw_cyclonedds & cyclonedds (they certainly should) https://github.com/ros2/ros2/pull/1025 

The wstring issues with Connext/Cyclone interop are known and have simply been excluded in Foxy. https://ci.ros2.org/job/ci_linux/12696/

**Comment by mjcarroll** [comment]
Yes, I'm going to check with @nuclearsandwich because he clearly has it fixed in Dashing, so it's likely an easy fix for Eloquent. I can work on that today, and the other tests are known issues.

**Comment by mjcarroll** [comment]
Rebuilding similar to Dashing:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12719/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7680/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10433/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12666/)

**Comment by nuclearsandwich** [comment]
Driving by the mention and noticed that there was an extra dash in `---ctest-args` Third time lucky?

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12726/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7687/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10440/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12673/)

**Comment by nuclearsandwich** [comment]
> Yes, I'm going to check with @nuclearsandwich because he clearly has it fixed in Dashing,

My "fix" is to disable linters in Dashing builds since we generally don't backport linter-only fixes.

**Comment by JWhitleyWork** [comment]
@mjcarroll Looks like everything made it (with the known exceptions). Good to merge?

**Comment by mjcarroll** [comment]
Thanks for the contribution and the patience.

**Comment by JWhitleyWork** [comment]
And thanks for the reviews and help!

**Comment by wjwwood** [comment]
I just merged the cyclonedds (https://github.com/ros/rosdistro/pull/27238) and rmw_cyclonedds (https://github.com/ros/rosdistro/pull/27237) entries from ros/rosdistro.

**Comment by JWhitleyWork** [comment]
@wjwwood Thank you, sir!

**Pull request merged**
