### PR TITLE
Update to Fast-DDS 2.1.x

### PR DESCRIPTION
**Pull request by jacobperron**
@EduPonz Let me know if this change looks good to you and I'll trigger CI.

### CODE REVIEW

**Review by EduPonz — APPROVED** [review]
LGTM! Thanks!

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13066/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8012/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10789/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13046/)

**Comment by jacobperron** [comment]
@EduPonz It looks like `rmw_fastrtps_shared_cpp` is failing to build.

**Comment by MiguelCompany** [comment]
@jacobperron This should have been fixed on eProsima/Fast-DDS@30c143f8fabd568ef357e94e787878f181fa0b3b

**Comment by jacobperron** [comment]
@MiguelCompany Thanks. Looks like there's still an issue with the Windows build:

```
C:\ci\ws\install\include\fastdds/rtps/builtin/discovery/endpoint/EDP.h(32,10): fatal error C1083: Cannot open include file: 'foonathan/memory/container.hpp': No such file or directory
```

**Comment by MiguelCompany** [comment]
@jacobperron The only difference I've seen is that `--merge-install` is only used on Windows.

I've been investigating a bit, and checked that adding `foonathan_memory` [here](https://github.com/ros2/rmw_fastrtps/blob/47be8ba4ed14303659e29094e72033b56449c15a/rmw_fastrtps_shared_cpp/CMakeLists.txt#L94) also solves the problem. I don't know if that would be the best solution, though, as the error comes from including a header that is not necessary. That's why I have created ros2/rmw_fastrtps#487 instead.

Is my reasoning correct?

**Comment by jacobperron** [comment]
Certainly ros2/rmw_fastrtps#487 makes sense.

Considering `rmw_fastrtps` does not directly depend on `foonathan_memory`, we should have to explicitly link against `foonathan_memory`. Sounds like maybe  `fastdds` is not exporting all the necessary info about it's dependency on `foonathan_memory`, and doing a merge install revealed this. This is just all speculation though, I haven't dug into it.

**Comment by MiguelCompany** [comment]
@jacobperron Now that ros2/rmw_fastrtps#487 has been merged, could you relaunch CI on this one?

**Comment by jacobperron** [comment]
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/13139/)

**Comment by EduPonz** [comment]
Hi @jacobperron @clalancette ,

Is their any blocker for this? Anything we can do on our side?

**Comment by clalancette** [comment]
Let me run CI on the whole thing again and see what it looks like:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13393/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8313/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11116/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13446/)

**Comment by clalancette** [comment]
All right, the failures on Windows are well-known.  So I'm going to go ahead and merge this in.

**Review by clalancette — APPROVED** [review]

**Comment by EduPonz** [comment]
Awesome!

**Pull request merged**
