### PR TITLE
Humble release versions 2023-07-18

### PR DESCRIPTION
**Pull request by audrow**
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19188/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13749/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19932/)
* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/450/)

Packaging:
* https://ci.ros2.org/view/packaging/job/packaging_linux/3102/
* https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/2469/
* https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/1602/
* https://ci.ros2.org/view/packaging/job/packaging_windows/2928/
* https://ci.ros2.org/view/packaging/job/packaging_windows_debug/1887/

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
It looks like we are missing a source release for ros2cli; that is, https://github.com/ros/rosdistro/pull/38016 should probably be closed, a source release done, and then a new `bloom-release` done.  Then we can update the version here.

**Review by clalancette — COMMENTED** [review]
There's no way you could have known this, but just this morning I ended up merging a change into https://github.com/ament/google_benchmark_vendor for humble.  My suggestion is to release that change as well.

**Comment by audrow** [comment]
Okay, I'll release it.

**Comment by audrow** [comment]
Here's a results from running my script that compares rosdistro and ros2.repos versions. Note the following have PRs
* https://github.com/ros/rosdistro/pull/38027
* https://github.com/ros/rosdistro/pull/38024
* https://github.com/ros/rosdistro/pull/38026
* https://github.com/ros/rosdistro/pull/38025

```
Comparing versions for humble...
 - google_benchmark_vendor has a version mismatch:
        0.1.1 (rosdistro)       !==     0.1.2 (ros2.repos)
 - Fast-DDS has a version mismatch:
        2.6.5 (rosdistro)       !==     2.6.4 (ros2.repos)
 - foonathan_memory_vendor has a version mismatch:
        1.2.0 (rosdistro)       !==     1.3.1 (ros2.repos)
 - osrf_pycommon has a version mismatch:
        2.0.2 (rosdistro)       !==     2.1.3 (ros2.repos)
 - rmw_connextdds has a version mismatch:
        0.11.1 (rosdistro)      !==     0.11.2 (ros2.repos)
 - ros2cli has a version mismatch:
        0.18.6 (rosdistro)      !==     0.18.7 (ros2.repos)
 - rosbag2 has a version mismatch:
        0.15.6 (rosdistro)      !==     0.15.7 (ros2.repos)

Skipped the following repos:
 - system_tests
```

**Review by clalancette — APPROVED** [review]
This looks good to me when we get green CI.

**Comment by audrow** [comment]
Once https://github.com/ros2/ci/pull/721 is merged in, I'll rerun the RHEL jobs again.

**Pull request merged**
