### PR TITLE
added use of compiler warnings plugin in jenkins

### PR DESCRIPTION
**Pull request by wjwwood**
This adds entries in the job configs to parse compiler warnings out of the job console output. On Linux it parses GCC 4 and on OS X it parses clang. There is no support for Windows.

@dirk-thomas If this works out I need to add this plugin to the list for setting up the build farm. Where is that list?

### CODE REVIEW

**Comment by wjwwood** [comment]
You can see the trend on the project pages:

http://54.183.26.131:8080/job/ros2_batch_ci_osx/
http://54.183.26.131:8080/job/ros2_batch_ci_linux/

**Comment by dirk-thomas** [comment]
LGTM

The Jenkins plugins are specified in the buildfarm_deployment repository in a puppet file: https://github.com/ros-infrastructure/buildfarm_deployment/blob/29b0cc1a110f7abeef444a3af4a497c155c30743/master/manifests/site.pp#L87

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
I also added an entry for Windows (I previously didn't notice the `MSBuild` option).

**Pull request merged**
