### PR TITLE
Add rosidl_runtime_py

### PR DESCRIPTION
**Pull request by jacobperron**
Connects to https://github.com/ros2/rosidl_python/issues/40

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Same question as in https://github.com/ros2/ros2/pull/781#issuecomment-533246546

**Comment by nuclearsandwich** [comment]
> Same question as in [#781 (comment)](https://github.com/ros2/ros2/pull/781#issuecomment-533246546)

In general I'd like to preserve the repository layout in Dashing but if there is enough activity on this repository that we want to backport the split for ease of maintenance I won't stand in the way.

**Comment by jacobperron** [comment]
I'm okay with leaving it for now. It consists of about 450 lines of python code, so hopefully any backports aren't too much trouble :crossed_fingers:

**Comment by jacobperron** [comment]
CI: https://github.com/ros2/rosidl_python/pull/88#issuecomment-533255464

**Comment by jacobperron** [comment]
I realized too late that I didn't have an approval on this, but I already merged https://github.com/ros2/rosidl_python/pull/88 :grimacing:

**Pull request merged**
