### PR TITLE
rebase all repos to master which must succeed

### LINKED ISSUE #78: should the CI jobs automatically rebase to master
Currently the CI job tests the code from the specified branches. If they are not up-to-date but branches earlier and master has diverged that is not covered by the test. The result is that the CI job might succeed but after merging the branch the CI job might fail on master.

Would it be sufficient to always do this after switching to the to-be-tested branches:

    vcs custom --git --args rebase master

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #78.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
If this must pass should we handle the return code?

**Comment by dirk-thomas** [comment]
We don't have to. Only if passed `exit_on_error=False` the script can continue. If the command fails it will `sys.exit()` already.

**Comment by tfoote** [comment]
+1

**Pull request merged**
