### PR TITLE
Add version, required by vcs tool

### PR DESCRIPTION
**Pull request by gerkey**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by jacquelinekay** [comment]
uh oh, sorry about that. why wasn't this tested when I ran CI for the branch that introduced this repo?

**Comment by dirk-thomas** [comment]
The CI jobs @jacquelinekay triggered passed. Maybe @gerkey can comment why it didn't work for him?

The missing version is not a problem imo. But we should specify it to prevent sudden changes if e.g. the default branch of the repo changes.

**Comment by gerkey** [comment]
The `vcs` tool seems to demand a `version` field:

~~~
gerkey@rossum:/tmp/ws$ ls
foo.repos
gerkey@rossum:/tmp/ws$ cat foo.repos 
repositories:
  ros2/tlsf:
    type: git
    url: https://github.com/ros2/tlsf.git
gerkey@rossum:/tmp/ws$ mkdir src
gerkey@rossum:/tmp/ws$ vcs import src < foo.repos 
=== src/ros2/tlsf (git) ===
Repository data lacks the 'version' value
gerkey@rossum:/tmp/ws$ find .
.
./foo.repos
./src
~~~

Adding the `version` field make `vcs` happy.

I don't know what's different on the CI job...

**Comment by dirk-thomas** [comment]
What version of vcstool are you using? The CI job will use the latest one.

**Comment by gerkey** [comment]
~~~
$ vcs --version
vcs 0.1.14
~~~

**Comment by gerkey** [comment]
I upgraded to `vcs` 0.1.15 and now it will import without the `version` field.

**Pull request merged**
