### PR TITLE
add rviz repository

### PR DESCRIPTION
**Pull request by wjwwood**
This will require some changes to ros2/ci, maybe https://github.com/ros2/ci/pull/117 as a starting place.

### CODE REVIEW

**Comment by wjwwood** [comment]
Since it's disable on Windows, I can go ahead and test that:

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3813/)

**Comment by wjwwood** [comment]
Here's a Linux job too:

- Linux: [Build Status](http://ci.ros2.org/job/ci_linux/3715/)

**Comment by wjwwood** [comment]
macOS CI:

- macOS: [Build Status](http://ci.ros2.org/job/ci_osx/3052/)

**Comment by wjwwood** [comment]
First pass at all platforms CI (no connext still as I bet there are compiler warnings or something I missed):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3719/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/877/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3055/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3815/)

**Comment by wjwwood** [comment]
Another round of CI with some fixes to code changes merged today:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3723/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/882/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3060/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3821/)

**Comment by wjwwood** [comment]
Yet another CI (full one this time):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3726/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/884/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3065/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3825/)

**Comment by wjwwood** [comment]
This is on hold until I can sort out the issues in the latest set of builds (hopefully tomorrow).

**Comment by wjwwood** [comment]
Ok, this should be (hopefully) the last set of full CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3745/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/894/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3085/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3839/)

**Comment by wjwwood** [comment]
One more time, with a CMake warning fixed and a new way to use the system tinyxml2 (avoiding building it at all):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3748/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/896/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3088/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3842/)

@mikaelarguedas

**Comment by mikaelarguedas** [comment]
:champagne: :champagne: :tada: :tada:

**Comment by wjwwood** [comment]
aarch64 test failures are flaky, so I'll merge this ❗️

**Pull request merged**
