### PR TITLE
Galactic Patch Release 1

### PR DESCRIPTION
**Pull request by cottsay**
Ubuntu: [Build Status](https://ci.ros2.org/job/ci_packaging_linux/462/)
Ubuntu aarch64: [Build Status](https://ci.ros2.org/job/ci_packaging_linux-aarch64/70/)
RHEL (CentOS): [Build Status](https://ci.ros2.org/job/ci_packaging_linux-rhel/29/)
Windows Release: [Build Status](https://ci.ros2.org/job/ci_packaging_windows/174/)
Windows Debug: [Build Status](https://ci.ros2.org/job/ci_packaging_windows/175/)

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@cottsay Could we also bump Fast DDS to v2.3.3? There have been several bug fixes, and branch `2.3.x` is used on the nightlies...

**Comment by cottsay** [comment]
> Could we also bump Fast DDS to v2.3.3?

Galactic was [frozen for stabilization in rosdistro a week ago](https://discourse.ros.org/t/preparing-for-galactic-sync-and-patch-release-2021-07-08/21273) - it's too late for any features fixes that don't resolve regressions since the previous release. I highly encourage you to get your changes **released** well in advance of the freeze date so that they can be tested in the binary packages prior to the sync or patch release.

**Comment by EduPonz** [comment]
Hi @cottsay ,

We'll definitely do that. Is there some kindo of schedule for patch releases or any approximate date you can give us presently?

**Comment by cottsay** [comment]
> Is there some kind of schedule for patch releases or any approximate date you can give us presently?

Both syncs and patch releases happen "as needed", but syncs typically happen more often. As Galactic is growing fairly quickly, we'll probably consider another sync in a couple of weeks or so.

Patch releases are a little different because only changes to core packages are a part of them, so they happen less often. We're hoping to merge some changes to rclpy soon, so it might not be long until we're considering another patch release as well, though surely not for at least a couple of weeks to give those changes time for proper testing.

**Comment by EduPonz** [comment]
Sure, that makes total sense. Thank you!

**Pull request merged**
