### PR TITLE
Switch to tracking master branch of ros2_tracing instead of release tag

### PR DESCRIPTION
**Pull request by christophebedard**
See #957

### CODE REVIEW

**Comment by christophebedard** [comment]
Here we go! @nuclearsandwich please let me know if I did anything wrong.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11633/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6763/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9519/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11618/)

**Comment by christophebedard** [comment]
It looks like the ci_linux job failed because of an unrelated issue. @nuclearsandwich should I just hit "rebuild" on https://ci.ros2.org/job/ci_linux/11633/ in this case?

**Comment by nuclearsandwich** [comment]
> It looks like the ci_linux job failed because of an unrelated issue. @nuclearsandwich should I just hit "rebuild" on [ci.ros2.org/job/ci_linux/11633](https://ci.ros2.org/job/ci_linux/11633/) in this case?

Yes that's exactly what I would do if this happened on one of my jobs.

**Comment by christophebedard** [comment]
Rebuild:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11663/)

**Pull request merged**
