### PR TITLE
add option to select CMake build type

### PR DESCRIPTION
**Pull request by dirk-thomas**
Release build: http://ci.ros2.org/job/ci_linux/898/
Debug build: http://ci.ros2.org/job/ci_linux/899/

### CODE REVIEW

**Comment by wjwwood** [comment]
Should this information be put into the description setter? https://github.com/ros2/ros2/blob/ci_scripts_cmake_build_type/job_templates/ci_job.xml.template#L74

**Comment by dirk-thomas** [comment]
Good point, added https://github.com/ros2/ros2/blob/597f13ad1a2d191da1624114152e02bb5f50c9b3/job_templates/ci_job.xml.template#L85

**Comment by wjwwood** [comment]
lgtm

**Comment by dirk-thomas** [comment]
Fix missing argument for launcher job: 3de1d990bdfa534760ca33c6642500133253b527

**Comment by dirk-thomas** [comment]
Pass cmake build type parameter to windows script: 0556ee7ecde4c281bc9f3068579c910927be6d4d

**Comment by wjwwood** [comment]
@dirk-thomas looks like the launcher is broken now? See the console output:

http://ci.ros2.org/job/ci_launcher/296/console
> java.lang.IllegalArgumentException: Illegal choice for parameter CI_CMAKE_BUILD_TYPE:
> ...

**Comment by dirk-thomas** [comment]
See #187.

**Pull request merged**
