### PR TITLE
Robot state publisher

### PR DESCRIPTION
**Pull request by Karsten1987**
This adds the robot_state_publisher and its dependencies for the `robot_state_publisher`.

This connects to https://github.com/ros2/demos/pull/118

### CODE REVIEW

**Comment by wjwwood** [comment]
Why not `robot_state_publisher` also?

**Comment by wjwwood** [comment]
Nevermind, looks like `robot_state_publisher` is in there too.

**Comment by mikaelarguedas** [comment]
is `tinyxml_vendor` still needed ? (now that we have chocolatey packages for windows and upstream packages for Linux and MacOS)

**Comment by mikaelarguedas** [comment]
also one dependant PR is still to be merged https://github.com/ros2/ci/pull/34

**Comment by Karsten1987** [comment]
@wjwwood the last linux build took 47 mins, max was 1h02min. So i guess this is pretty much in range.

@mikaelarguedas As it's only a vendor package it's not strictly necessary, but also doesn't do any harm within this scope of this PR. I think it's a general decision to which extend we provide `choco`, `*-vendor` or just `ros2-*` packages. For now I'll follow the principle of `poco-vendor`, but I agree we can open a separate PR for removing tinyxml_vendor dependencies, with the cost of providing a `findTinyXML.cmake` and the dependency to `cmake_modules`.

**Comment by mikaelarguedas** [comment]
@Karsten1987 FYI: this failed to compiled on several nightlies:
http://ci.ros2.org/view/nightly/job/nightly_win_deb/417/ : timestamp 07:33:23
http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/626/consoleFull: timestamp 07:32:39

And added a bunch of cpplint & uncrustify test failures on the jobs that compiled successfully: http://ci.ros2.org/view/nightly/job/nightly_linux_debug/398/testReport/

**Comment by wjwwood** [comment]
@Karsten1987 CI is failing for OS X on dosa:

http://ci.ros2.org/job/ci_osx/1818/

Did you forget to install the dependencies on that machine? I'm going to disable dosa until we can address that issue, to prevent failures.

**Comment by Karsten1987** [comment]
I am sorry for the trouble. Don't know what's happening with dosa. This looks like plain compiler errors rather than debs missing. I don't have VPN to check the machine, I'll investigate it when I am back in the office.

**Comment by wjwwood** [comment]
@Karsten1987 no worries, it's not a time sensitive issue. I just disabled dosa for now. I can help you look into it tomorrow.

**Pull request merged**
