### PR TITLE
add cli_tools

### PR DESCRIPTION
**Pull request by gerkey**
Now that we're starting to use it, add the `cli_tools` repo to the standard repos file, so that it's in everybody's checkout and getting linted and tested. Related to ros2/cli_tools#2

### CODE REVIEW

**Comment by gerkey** [comment]
CI jobs using that repos file:

http://ci.ros2.org/job/ci_linux/2318/
http://ci.ros2.org/job/ci_osx/1774/
http://ci.ros2.org/job/ci_windows/2351/

**Comment by gerkey** [comment]
Sad Jenkins:
~~~
18:16:41 CMake Error at CMakeLists.txt:11 (find_package):
18:16:41   By not providing "Findc_utilities.cmake" in CMAKE_MODULE_PATH this project
18:16:41   has asked CMake to find a package configuration file provided by
18:16:41   "c_utilities", but CMake did not find one.
~~~

I didn't notice the new dependency because I hadn't recently pulled master  on `cli_tools` in my workspace.

@Karsten1987, what's your plan with `c_utilities`? Should we add that to the repos file now, too?

**Comment by Karsten1987** [comment]
Yes, I'd add `c_utilities`. I believe this should also become handy in the near future.

**Comment by gerkey** [comment]
bba2162 adds `c_utilities`. And this time I locally built and tested the latest versions :)

New CI:

http://ci.ros2.org/job/ci_linux/2319/
http://ci.ros2.org/job/ci_osx/1775/
http://ci.ros2.org/job/ci_windows/2352/

**Comment by gerkey** [comment]
The OSX build failed with what look like GitHub connectivity issues. New job:

http://ci.ros2.org/job/ci_osx/1776/

**Comment by clalancette** [comment]
For some reason, that particular failure seems to be persistent on the OSX
nodes.  Over the last 4 days, we've had several jobs fail, always on OSX,
being unable to contact GitHub.  I highly doubt GitHub has been having
problems that much, so I suspect one of the build nodes is having
hardware/OS problems.  Once your new job is complete, I'll go in and reboot
them to see if that helps at all.

--
Chris Lalancette

clalancette@osrfoundation.org

Open Source Robotics Foundation
170 S Whisman Rd
Building D, Suite A
Mountain View, CA 94041
USA

**Comment by mikaelarguedas** [comment]
NOTE: the problem shows up only on mini2, so no need to restart/investigate the other OSX nodes

**Comment by gerkey** [comment]
@clalancette, thanks for the background and the offer to look into it!

The CI jobs are good, so I'll merge.

**Pull request merged**
