### PR TITLE
Bump versions for Iron Patch 4

### PR DESCRIPTION
**Pull request by Yadunund**
TODO:
- [x] Source release and bloom `rosbag2`: https://github.com/ros2/rosbag2/pull/1568
- [x] CI job with new ros2.repos file after PR is approved
- [x] Packaging job after CI passes
- [ ] Tag source release and upload tarballs
- [x] Run Irel sync job to sync binaries from testing to main.
- [x] Merge https://github.com/ros/rosdistro/pull/39799#event-11721341403

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
This all looks good to me, once the rosbag2 release is done.

**Comment by Yadunund** [comment]
Will trigger a rebuild of the jobs above.

**Comment by Yadunund** [comment]
CI job started with: https://raw.githubusercontent.com/ros2/ros2/yadu/iron-patch-4/ros2.repos

CI:
* Linux [Build Status](https://ci.ros2.org/job/ci_linux/20253/)
* Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/14669/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/20977/)
* RHEL-9 [Build Status](https://ci.ros2.org/view/All/job/ci_linux-rhel/577/)

Will run packaging jobs after CI passes.

**Review by clalancette — APPROVED** [review]

**Comment by Yadunund** [comment]
Packaging jobs:
- Linux [Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux/3329/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/2687/)
- RHEL [Build Status](https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/1828/)
- Windows [Build Status](https://ci.ros2.org/view/packaging/job/packaging_windows/3142/)
- Windows debug [Build Status](https://ci.ros2.org/view/packaging/job/packaging_windows_debug/2102/)

**Pull request merged**
