### PR TITLE
Track upstream repository for orocos_kdl

### LINKED ISSUE #937: sync orocos_kdl with upstream
To benefit from change landed upstream: e.g. orocos/orocos_kinematics_dynamics#255

The alternative would be to replace the fork with a branch hosted upstream and maintained by the maintainers of that repo.

### PR DESCRIPTION
**Pull request by jacobperron**
Fixes #937

Related to https://github.com/ros2/orocos_kinematics_dynamics/pull/24

Depends on:

- https://github.com/ros2/orocos_kdl_vendor/pull/1
- https://github.com/ros2/geometry2/pull/473
- https://github.com/ros/kdl_parser/pull/58
- https://github.com/ros/robot_state_publisher/pull/191
- ~~https://github.com/ros2/ci/pull/599~~

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16517/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11104/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/16893/)

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
>     1. Depend on system package and vendor orocos_kdl for Windows

If orocos-kdl is suitably available on most of our host platforms then I would absolutely advocate for an explicit vendor package as the way forward. It doesn't seem like RHEL 8 or EPEL8 currently have an orocos-kdl-devel package or similar so we're at 50% availability or 60% if you count macOS, which I have not been anymore. We're working with the RoboStack folks to make conda the primarily supported installation method on Windows and orocos-kdl is [packaged on conda-forge](https://anaconda.org/conda-forge/orocos-kdl) so depending on whether we can get the package in EPEL there's a long term possibility for removing the vendor package after a certain point.

I'm very in favor of the vendor package approach. If orocos-kdl is one of the packages particularly sensitive to the downsides of ExternalProject_Add then it may be that we allocate some time to the ament_cmake wrapper/alternative which was discussed offline previously.

**Comment by nuclearsandwich** [comment]
>     * Since orocos_kdl contains a git submodule for pybind11, infrastructure and docs should be updated to use
>       `vcs import --recurse`.

This sends shivers down my spine. Is there no way to point it at a system or already-vendored pybind11 installation?

**Comment by jacobperron** [comment]
>  Is there no way to point it at a system or already-vendored pybind11 installation?

I'll look into this; I suspect it may require some changes to oroco_kdl upstream.

**Comment by jacobperron** [comment]
I've created a vendor package for orocos_kdl (https://github.com/ros2/orocos_kdl_vendor/pull/1).
It does not currently handle `python_orocos_kdl`, but it doesn't look like we're depending on the Python bindings yet so maybe that's not a deal breaker.

Correct me if I'm wrong, but I think for this to work as desired, we should add rosdep keys for `orocos_kdl` and `python_orocos_kdl` pointing to system packages.

---

I've also proposed a patch upstream to avoid building pybind11 if it is already available on the system (https://github.com/orocos/orocos_kinematics_dynamics/pull/375).

**Comment by nuclearsandwich** [comment]
> I've also proposed a patch upstream to avoid building pybind11 if it is already available on the system ([orocos/orocos_kinematics_dynamics#375](https://github.com/orocos/orocos_kinematics_dynamics/pull/375)).

You have my exquisite gratitude for this. :bow: :bow:	:bow:	



> Correct me if I'm wrong, but I think for this to work as desired we should add rosdep keys for `orocos_kdl` and `python_orocos_kdl` pointing to system packages.

Yes, the vendor package should declare build and runtime dependencies on the system packages it provides so it can, essentially, re-export those dependencies when they are present and when they're not it should also declare build dependencies on the vendored package's build dependencies so it can be built when the system packages aren't available.

**Comment by jacobperron** [comment]
I've updated this PR to switch to the vendor packages, updated other ROS 2 packages depending on orocos_kdl, and triggered CI (see updated ticket description).

Seems like the last roadblock is Windows CI, failing to build PyKDL with:

```
21:34:28   CMake Error at C:/ci/ws/install/share/cmake/pybind11/pybind11Tools.cmake:119 (set_property):
21:34:28     Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
21:34:28     "debug".  The INTERFACE_LINK_LIBRARIES property may contain
21:34:28     configuration-sensitive generator-expressions which may be used to specify
21:34:28     per-configuration rules.
```

@MatthijsBurgh Any insight into this error?

**Comment by jacobperron** [comment]
I've opened a PR upstream to fix the CMake warnings: https://github.com/orocos/orocos_kinematics_dynamics/pull/385

**Comment by MatthijsBurgh** [comment]
@jacobperron I am not developing any software on Windows. So I can't help you with this one.

**Comment by jacobperron** [comment]
Alright, thanks to @sloretz we are now successfully building on Windows :tada: 

There are now [22 MSBuild warnings](https://ci.ros2.org/job/ci_windows/16708/msbuild/) to resolve upstream and a [few cmake lint test failures](https://ci.ros2.org/job/ci_windows/16708/testReport/) in the vendor package. I should be able to resolve the remaining warnings and test failures. I think we just need reviews on this and the connected PRs (see PR description).

@clalancette @nuclearsandwich Is there anything else that we should do and/or do you have any reservations about actually vendoring orocos_kdl (versus just releasing upstream as a ROS 2 package)?

**Comment by jacobperron** [comment]
I've opened a PR upstream to try and resolve MSBuild warnings: https://github.com/orocos/orocos_kinematics_dynamics/pull/390

**Comment by jacobperron** [comment]
https://github.com/orocos/orocos_kinematics_dynamics/pull/391 addresses another CMake warning.

**Comment by jacobperron** [comment]
CI is green except for one Cmake warning coming from pybind11. I'll see if we can quiet the warning in `python_orocos_kdl_vendor`.

**Comment by jacobperron** [comment]
> CI is green except for one Cmake warning coming from pybind11. I'll see if we can quiet the warning in python_orocos_kdl_vendor.

Resolve in https://github.com/orocos/orocos_kinematics_dynamics/pull/392

**Review by sloretz — APPROVED** [review]

**Pull request merged**
