### PR TITLE
Add ignition math6 and cmake2 vendor packages

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

Add ignition math6 and cmake2 vendor packages. This dependency is required by this PR in RVIZ2 https://github.com/ros2/rviz/pull/751

### CODE REVIEW

**Comment by cottsay** [comment]
I think we should add a new subdirectory for ignition packages instead of dumping them in the `ros2` directory. Thoughts?

**Comment by ahcorde** [comment]
@cottsay, is `ignition` a good name ?

**Review by cottsay — APPROVED** [review]

**Comment by ahcorde** [comment]
Rerunning CI here https://github.com/ros2/rviz/pull/751#issuecomment-919275138

**Review by clalancette — APPROVED** [review]
Looks good with green CI.  I'll suggest that in addition to the normal CI, we also run Windows Debug and RHEL CI.

**Comment by ahcorde** [comment]
CI is green https://github.com/ros2/rviz/pull/751#issuecomment-919471889 Merging!

**Comment by clalancette** [comment]
> Looks good with green CI. I'll suggest that in addition to the normal CI, we also run Windows Debug and RHEL CI.

Unfortunately, it looks like Windows CI is yellow because of this change.  @ahcorde can you look into it?

**Comment by ahcorde** [comment]
> > Unfortunately, it looks like Windows Debug CI is yellow because of this change. @ahcorde can you look into it?
> 
> Also it looks like the Windows packaging builds went yellow because of this: https://ci.ros2.org/view/packaging/job/packaging_windows/2239/msbuild/

FYI @clalancette  https://github.com/ignition-release/ignition_cmake2_vendor/pull/1

**Pull request merged**
