### PR TITLE
Update ros2_tracing to 0.2.12

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Getting ahead of releasing a new version to address fixes in CI. There
are other changes to be tested as well however.

Before this is merged, we should update the PR to use the release tag once it is made.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8853/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4648/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7249/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8767/)

This will replace #837 since the released version will include those changes.

**Comment by dirk-thomas** [comment]
We decide to not track master but the latest release in the past. If the rational hasn't changed I don't think it should be switched.

**Comment by christophebedard** [comment]
@nuclearsandwich the tag `0.2.12` is ready and the rosdistro PR is up: https://github.com/ros/rosdistro/pull/23259

**Comment by nuclearsandwich** [comment]
> We decide to not track master but the latest release in the past. If the rational hasn't changed I don't think it should be switched

It seems like you did not read the pull request description. I opened the PR (in draft state) so I had somewhere to share CI results with the intent to update to the released tag when it became available.

**Comment by nuclearsandwich** [comment]
The test failures in the above CI are known and accounted for and the specific linter failures in ros2_tracking are resolved with this release.

**Pull request merged**
