### PR TITLE
use Connext 5.2 pro

### PR DESCRIPTION
**Pull request by dirk-thomas**
Use RTI Connext 5.2 Professional on the windows slave.

Together with ros2/rmw_connext#75: ~~http://ci.ros2.org/job/ros2_batch_ci_windows/164/~~ http://ci.ros2.org/job/ros2_batch_ci_windows/187/

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
23 CI jobs later this actually started to work...

**Pull request merged**
