### PR TITLE
use --retest-... options

### PR DESCRIPTION
**Pull request by dirk-thomas**
Non-nightly jobs will retry 5 times if any test fails.

Nightly jobs will run all tests up to 20 times (if none fails).

Please review.

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
The test args worked for the nightly job: http://ci.ros2.org/view/nightly/job/nightly_linux_debug/121/

The console output nicely shows that some of the flaky pub/sub tests fail initially but pass on repeated tries (search for "`again (retry`").

**Comment by dirk-thomas** [comment]
The `--ament-build-args` argument parsing doesn't work right now. Will look at it soon...

**Comment by dirk-thomas** [comment]
Fixed spelling of argument: 372be8061fb51296f5219401dd8b17e3ecb45e7e

**Pull request merged**
