### PR TITLE
Add nightly versions of packaging jobs, #146

### PR DESCRIPTION
**Pull request by gerkey**
I have no idea how to test this change.  Do we just run it, see what happens, then revert if something went wrong?

Feedback most welcome.

### CODE REVIEW

**Comment by tfoote** [comment]
Yeah, you could spin up a test farm to test it, but otherwise you deploy and see how it looks.

**Comment by dirk-thomas** [comment]
Why does it need to be a separate set of jobs? Can we not just trigger the existing ones nightly (beside manually)?

**Comment by gerkey** [comment]
@dirk-thomas , do you mean that I could add the `time_trigger_spec` setting to the existing jobs, then it would be both nightly and triggerable on demand?  I've never used Jenkins in this way, so I don't know what's possible.

**Comment by dirk-thomas** [comment]
Yes, the time-based trigger is orthogonal to triggering it manually.

**Comment by gerkey** [comment]
Then I would seem to have two options regarding email notification (if I'm interpreting the code correctly): send email to `ros@` for all packaging jobs, or don't send email to anyone on the nightly packaging jobs.  I'm inclined to go with no email.  Thoughts?

**Comment by dirk-thomas** [comment]
I would suggest the same notification setting as for the CI jobs. They notify ros@... when they fail or are unstable (and for the first stable build after a non-stable period). Otherwise nobody will notice if these jobs are not green.

**Comment by gerkey** [comment]
cf5d1e8

**Comment by dirk-thomas** [comment]
+1

**Comment by dirk-thomas** [comment]
I had to add the necessary snippet to the job template to make this work: cc26353b00074e3d5dbb620fab41bba86c120454

Now +1.

**Comment by gerkey** [comment]
Thanks for the fix!

**Comment by dirk-thomas** [comment]
This patch was incomplete and didn't enable any email notification. Follow up ticket #183.

**Pull request merged**
