### PR TITLE
Spaceros

### PR DESCRIPTION
**Pull request by Maclain27**
**maclain27**said:

> let this repository to readme as new developer  in Ros READ this pull requests !

### CODE REVIEW

**Comment by aprotyas** [comment]
The `spaceros` branch already exists with these commits, and this PR is targeting the wrong branch. I'll close this one out.

**Comment by Maclain27** [comment]
- why did you closed it!?

**Comment by Maclain27** [comment]
> - why did you closed it!?

**Comment by aprotyas** [comment]
This PR is not necessary because there is a branch which houses all of these commits - [`spaceros`](https://github.com/ros2/ros2/tree/spaceros). The `master` branch does NOT specify package information for the Space ROS distribution.

**Pull request closed without merging**
